### ISSUE TITLE
Low contrast on headerbar

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/python-tester#1]
The default text color is very low contrast against the darker blue.

## Before

![image](https://user-images.githubusercontent.com/611168/52380374-baa6d700-2a2a-11e9-94c8-42bad11ae4b9.png)

## After
```css
@define-color textColorPrimary @BANANA_300;
@define-color textColorPrimaryShadow alpha(shade(@colorPrimary, 0.6), 0.4);

.titlebar button.combo * {
  color: inherit;
}
```

![image](https://user-images.githubusercontent.com/611168/52380351-aa8ef780-2a2a-11e9-8589-10cec93f7b4c.png)
